import type { Metadata } from "next";
import { Arsenal } from "next/font/google";

import "./globals.css";

export const arsenal = Arsenal({
  weight: ["400", "700"],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={arsenal.className}>{children}</body>
    </html>
  );
}
